# writing anything in this will override the variables
# We remember you that all these variables can be set handly from the
# configuration process. Check ./configure --help for available features.

# Fundamental variables are:
# FFLAGS
# FF
# EXTRA_LIBS
# CAMPARI_HOME
#
